FROM haskell:8 AS build
ENV HOME /
COPY . /src
WORKDIR /src
RUN stack --install-ghc build
RUN stack install

FROM haskell:8 AS runner
COPY --from=build /.local/bin/* /bin/
ENTRYPOINT ["/bin/HaskellDemo-exe"]
